version: '3'
services:
  idbacanalysis-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idbacanalysis-streamlit
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /bin/bash -c "source activate python312 && /app/run_server.sh"
    environment:
      VIRTUAL_HOST: analysis.idbac.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: analysis.idbac.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net